"""empty message

Revision ID: a0c54435a84e
Revises: 
Create Date: 2024-06-12 13:31:01.905272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0c54435a84e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url_map', schema=None) as batch_op:
        batch_op.alter_column('short',
               existing_type=sa.TEXT(),
               type_=sa.String(length=16),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url_map', schema=None) as batch_op:
        batch_op.alter_column('short',
               existing_type=sa.String(length=16),
               type_=sa.TEXT(),
               existing_nullable=False)

    # ### end Alembic commands ###
